<?php

use Phelium\Component\MySQLBackup;

function hunter_backup($file, $tables = array(), $compress = 'zip', $target = 'default') {
  global $databases;
  $Dump = new MySQLBackup($databases[$target]['host'], $databases[$target]['username'], $databases[$target]['password'], $databases[$target]['database']);

  if(!empty($tables)){
    $Dump->addTables($tables);
  }

  if (!is_dir(dirname($file))){
    mkdir(dirname($file), 0755, true);
  }

  $Dump->setFilename($file);
  if($compress != false){
    $Dump->setCompress('zip');// zip | gz | gzip
  }

  $Dump->setDownload(true); // starts downloading
  $Dump->dump();
}
